from django.db import models

# Create your models here.

class Data(models.Model):
    cnt_cctv = models.IntegerField(default=0)
    cnt_light = models.IntegerField(default=0)
    cnt_crime = models.IntegerField(default=0)
    cnt_police = models.IntegerField(default=0)
    female_population = models.IntegerField(default=0)
    dense_population = models.IntegerField(default=0)
    cnt_population = models.IntegerField(default=0)
    cnt_notify = models.IntegerField(default=0)
    #
    gangnam = models.IntegerField(default=0)
    gangdong = models.IntegerField(default=0)
    gangbuk = models.IntegerField(default=0)
    gangseo = models.IntegerField(default=0)
    gwanak = models.IntegerField(default=0)
    gwangjin = models.IntegerField(default=0)
    guro = models.IntegerField(default=0)
    geumcheon = models.IntegerField(default=0)
    nowon = models.IntegerField(default=0)
    dobong = models.IntegerField(default=0)
    dongdaemun = models.IntegerField(default=0)
    dongjak = models.IntegerField(default=0)
    mapo = models.IntegerField(default=0)
    seodaemun = models.IntegerField(default=0)
    seocho = models.IntegerField(default=0)
    seongdong = models.IntegerField(default=0)
    seongbuk = models.IntegerField(default=0)
    songpa = models.IntegerField(default=0)
    yangcheon = models.IntegerField(default=0)
    yeongdeungpo = models.IntegerField(default=0)
    yongsan = models.IntegerField(default=0)
    eunpyeong = models.IntegerField(default=0)
    jongno = models.IntegerField(default=0)
    jung = models.IntegerField(default=0)
    jungnang = models.IntegerField(default=0)